### ISSUE TITLE
How to Pass Context Variable

### ISSUE THREAD

**Issue by einancunlu** [abynim/Sketch-PluginHelper#2]
Hello Aby,

I'm trying to use context variable after launching the pluginHelper.app, but couldn't find the way. 

The plugin window opens without error. Then when I press a button, I call the following `what()` method as you did in the example. But here my savedContext variable doesn't work (I save it in main.cocoascript).  

``` javascript
@import 'main.cocoascript'

function what() {
    var layer = savedContext.selection.firstObject()
    [doc showMessage: [layer name]]
}
```

Is there any way to reach context variable after pressing a button in plugin helper window? I guess we can't pass the context via JSON but not sure.

**Comment by abynim** [comment]
@einancunlu : That's a limitation with this approach. You can only pass JSON between Sketch and the helper app and it cannot contain any complex Sketch-specific objects. The only way is to fetch the context again when calling the `what()` method. 

To validate that the context hasn't changed, you could save certain parameters (like selected layer IDs, pageID, etc) to `userDefaults` and check for those when you call the `what()` method via the helper app.

**Comment by einancunlu** [comment]
Hmm, things got interesting. I realized that in `what()` method `selection` is reachable but not context. How can I fetch the context again in this method? 

I'm able to run another method using `runPluginCommandWithIdentifier:(NSString)identifier fromBundleAtURL:(NSURL)url` as there is an example [here](http://developer.sketchapp.com/reference/AppController/). I guess this can work for me too, is this same thing you're mentioning?

**Comment by abynim** [comment]
You can access `selection` but not the original `context` in the `what()` method because the way Helper.app calls the method is by creating a new temporary plugin. It uses the `runPluginScript:(NSString)script name:(NSString)name` method mentioned on the same link you referenced. This new temp plugin then gets its own `context`, but the `selection` remains the same (unless you manually changed selection before calling `what()`).

The `runPluginCommandWithIdentifier:(NSString)identifier fromBundleAtURL:(NSURL)url` method is a probably a better alternative since you will get a `context` specific to your plugin. The only drawback is that you will not be able to pass arguments when calling this method, since it requires that the plugin is already defined and referenced by the `identifier`.

**Comment by einancunlu** [comment]
Oh I see what you mean. I'm started to understand Xcode codes better now. I updated them for Swift 2 but wasn't so aware of all codes. 

After I put `context` parameter here, I'm able to get context now. 

``` Swift
    @IBAction func handleRedButton(sender: AnyObject) {
        var script  = "@import 'helperMethods.js'\n"
            script += "what(context)"

        // Save this script to a .js file
        if let scriptPath = SketchPlugin.createScriptWithText(...
    }
```

Thanks for explanations, I guess these are enough for me now. : )

**Comment by abynim** [comment]
Cool! Glad it helped :+1:
